language: node_js
node_js:
  - "4.3.2"
  - "5.0"
  - "node"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
     - chrome-linux
     - extension/node_modules
before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - ./lighthouse-core/scripts/download-chrome.sh
  - start-stop-daemon --start --background --exec $(pwd)/lighthouse-core/scripts/launch-chrome.sh
  - sleep 5
script:
  - npm run lint
  - if [[ $(node -v) =~ ^v4.* ]]; then npm run unit:harmony; else npm run unit; fi
  - npm run closure
  - if [[ $(node -v) =~ ^v4.* ]]; then npm run coveralls:harmony; else npm run coveralls; fi
  - npm run smoke
  - cd lighthouse-extension
  - gulp build
