packages:
  - "."
  - "lighthouse-logger"

allowBuilds:
  core-js: true
  esbuild: true
  protobufjs: true
  puppeteer: true



packageExtensions:
  puppeteer-core:
    dependencies:
      rxjs: "^7.8.2"

shamefully-hoist: true
