# The Travis CI is our full-fledged CI, but this Github workflow
# runs some basics (build, lint, diff sample json, and unit-core)
# and it should complete quickly, giving more immediate feedback
# than waiting for Travis

name: 💡🏠

on: [push]

jobs:
  basics:

    runs-on: ubuntu-latest
    strategy:
      # e.g. if lint fails, continue to the unit tests anyway
      fail-fast: false

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # Cache yarn deps. thx https://github.com/actions/cache/blob/master/examples.md#node---yarn
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up node_modules cache
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn --frozen-lockfile
    - run: yarn build-all
    - run: yarn bundlesize
    - run: yarn diff:sample-json
    - run: yarn tsc -p .
    - run: yarn lint
    # - run: yarn unit-core

    # - name: yarn test-clients
    #   uses: GabrielBB/xvfb-action@v1.0
    #   with:
    #     run: yarn test-clients
    
    # - name: yarn smoke
    #   uses: GabrielBB/xvfb-action@v1.0
    #   with:
    #     run: yarn smoke
    
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum yarn test-clients
    - run: xvfb-run --auto-servernum yarn smoke
    - run: xvfb-run --auto-servernum yarn test-bundle

    - run: yarn test-viewer
    - run: yarn test-lantern
    - run: yarn test-legacy-javascript
    - run: yarn i18n:checks
    - run: yarn dogfood-lhci
    - run: yarn test-docs

    # Fail if any changes were written to source files (ex, from: build/build-cdt-lib.js).
    - run: git diff --exit-code
