name: CI

on:
  push:
    branches: [main]
  pull_request: # run on all PRs, not just PRs to a particular branch

env:
  PUPPETEER_SKIP_DOWNLOAD: 1

jobs:
  # `basics` includes all non-smoke and non-unit CI
  basics:
    runs-on: ubuntu-latest
    env:
      CHROME_PATH: ${{ github.workspace }}/.tmp/chrome-tot/chrome
      FORCE_COLOR: true

    # A few steps are duplicated across all jobs. Can be done better when this feature lands:
    #   https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851
    #   https://github.com/actions/runner/issues/438
    steps:
    - name: git clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 100
    - run: bash core/scripts/github-actions-commit-range.sh
      env:
        GITHUB_CONTEXT_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_CONTEXT_BASE_SHA: ${{ github.event.before }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.5.2
      
    - name: Use Node.js 22.19
      uses: actions/setup-node@v4
      with:
        node-version: '22.19'
        cache: 'pnpm'

    - run: pnpm install --no-frozen-lockfile
    - run: pnpm type-check
    - run: pnpm build-all

    # Since Ubuntu 23, dev builds of Chromium need this.
    # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
    - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    # Run pptr tests using ToT Chrome instead of stable default.
    - name: Install Chrome ToT
      run: bash $GITHUB_WORKSPACE/core/scripts/download-chrome.sh

    - name: pnpm test-clients
      run: bash $GITHUB_WORKSPACE/.github/scripts/test-retry.sh pnpm test-clients
    - name: pnpm test-docs
      run: pnpm test-docs
    - name: pnpm test-treemap
      run: bash $GITHUB_WORKSPACE/.github/scripts/test-retry.sh pnpm test-treemap

    - run: pnpm diff:sample-json
    - run: pnpm diff:flow-sample-json
    - run: pnpm lint

    - run: pnpm test-legacy-javascript
      env:
        # https://github.com/nodejs/node/issues/51555#issuecomment-1974877052
        DISABLE_V8_COMPILE_CACHE: 1
    - run: pnpm i18n:checks
    - run: pnpm dogfood-lhci
    - run: pnpm generate-insight-audits

    # Fail if any changes were written to any source files or generated untracked files (ex, from: build/build-cdt-lib.js).
    - run: git add -A && git reset pnpm-lock.yaml core/scripts/legacy-javascript/ && git diff --cached --exit-code

    # buildtracker needs history and a common merge commit.
    - name: Fixup git history (for buildtracker)
      run: bash $GITHUB_WORKSPACE/.github/scripts/git-get-shared-history.sh
      env:
        # https://buildtracker.dev/docs/guides/github-actions#configuration
        BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}
    - name: Store in buildtracker
      # TODO(paulirish): Don't allow this to fail the build. https://github.com/paularmstrong/build-tracker/issues/200
      run: pnpm bt-cli upload-build || true
      env:
        # https://buildtracker.dev/docs/guides/github-actions#configuration
        BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}

    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
