# The Travis CI is our full-fledged CI, but this Github workflow
# runs the same tests. The GH workflow UI makes it simpler to hone
# in on the step that failed.

name: 💡🏠

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    # A lot of steps in common between all jobs. Can be done better when this feature lands:
    # https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851
    # https://github.com/actions/runner/issues/438
    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: yarn --frozen-lockfile
    - run: yarn build-all

    - name: Upload dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/

  unit:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      # e.g. if lint fails, continue to the unit tests anyway
      fail-fast: false

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/

    - run: yarn --frozen-lockfile

    - run: yarn diff:sample-json
    - run: yarn type-check
    - run: yarn lint
    - run: yarn test-lantern
    - run: yarn test-legacy-javascript
    - run: yarn i18n:checks

    - name: Setup protoc
      uses: arduino/setup-protoc@7ad700d
      with:
        version: '3.7.1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install protobuf==3.7.1

    - run: yarn test-proto # Run before unit-core because the roundtrip json is needed for proto tests.

    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum yarn unit

    # Run tests that require headfull Chrome.
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum yarn test-clients
    - run: xvfb-run --auto-servernum yarn test-bundle
    - run: xvfb-run --auto-servernum yarn test-docs

    - run: yarn dogfood-lhci

    # Fail if any changes were written to source files (ex, from: build/build-cdt-lib.js).
    - run: git diff --exit-code

    # buildtracker runs `git merge-base HEAD origin/master` which needs more history than depth=1. https://github.com/paularmstrong/build-tracker/issues/106
    - name: Deepen git fetch (for buildtracker)
      run: git fetch --deepen=100
    - name: Store in buildtracker
      # TODO(paulirish): Don't allow this to fail the build. https://github.com/paularmstrong/build-tracker/issues/200
      run: yarn bt-cli upload-build || true
      env:
        # https://buildtracker.dev/docs/guides/github-actions#configuration
        BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}


  smoke:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: yarn --frozen-lockfile

    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum yarn smoke --debug -j=1 --retries=2
