name: package-test

on:
  push: # TODO: remove before merge.
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  if: contains(github.context.payload.pull_request.title, '/^v\d+\.\d+\.\d+/')
  package-test:
    runs-on: ubuntu-latest
    name: Package Test

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: yarn install --frozen-lockfile --network-timeout 1000000
    - run: yarn build-report
    - run: sudo apt-get install xvfb

    - run: xvfb-run --auto-servernum bash $GITHUB_WORKSPACE/lighthouse-core/scripts/release/package-test.sh

    # Fail if any changes were written to source files.
    - run: git diff --exit-code
